# Generated by Django 2.2.3 on 2019-07-14 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='EnrollmentNo',
            new_name='enrollmentNo',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='Name',
            new_name='name',
        ),
    ]
