# Generated by Django 2.2.3 on 2019-07-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20190714_0747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderDate', models.DateField()),
                ('Region', models.CharField(max_length=10)),
                ('Rep', models.CharField(max_length=10)),
                ('Item', models.CharField(max_length=10)),
                ('Units', models.IntegerField()),
                ('UnitCost', models.FloatField()),
                ('Total', models.FloatField()),
            ],
        ),
    ]
